apiVersion: v1
kind: Service
metadata:
  name: transaction-streams
spec:
  selector:
    app: transaction-streams
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31920
  type: LoadBalancer