apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller
  labels:
    app: poller
  namespace: external
spec:
  type: ExternalName
  externalName: 10.0.2.2
  replicas: 1
  template:
    metadata:
      name: poller
      labels:
        app: poller
    spec:
      containers:
        - name: poller
          image: poller
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: SPRING_CLOUD_STEAM_KAFKA_BINDER_BROKERS
              value: 'PLAINTEXT://broker:9092'
      restartPolicy: Always
  selector:
    matchLabels:
      app: poller